name: Apply to terraform 
on:
  workflow_dispatch:
    inputs:
      environment:
        description: "server details"
        required: true
jobs:
  tf_plan: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: test the ${{github.event.inputs.environment}} environment
        env: 
          environment: ${{github.event.inputs.environment}}
        run: |
          echo: Hello, this is the ${{github.event.inputs.environment}}  server >> ${{env.environment}}.txt
      - name: upload a built artifact
        uses: actions/upload-artifact@v3.1.0
        with: 
          name: ${{github.event.inputs.environment}}
          path: ${{github.event.inputs.environment}}.txt
  tf_apply:
    runs-on: ubuntu-latest
    needs: tf_plan
    environment: ${{github.event.inputs.environment}}
    steps:
      - uses: actions/checkout@v3
      - name:  Download a Build Artifact
        uses: actions/download-artifact@v3.0.0
        with: 
          name: ${{github.event.inputs.environment}}
      - name: Apply the ${{github.event.inputs.environment}} env
        run: |
          cat ${{github.event.inputs.environment}}.txt
